-- Insert Admin User
INSERT INTO admins (username, password, email, name, created_at, updated_at)
VALUES (
  'admin',
  '$2a$10$uKw1YDG/SjSLSeMF3u8UjuenNFIMDYCDvDRl5qPAYC2dvl5AnmDdK',
  'admin@calbayog.gov.ph',
  'Super Admin',
  NOW(),
  NOW()
) ON CONFLICT (username) DO NOTHING;

-- Insert Hotels (Accurate Calbayog City coordinates: 12.0686°N, 124.5972°E)
INSERT INTO destinations (name, category, description, short_description, location_lat, location_lng, location_address, contact_phone, contact_email, contact_facebook, contact_website, opening_hours, entrance_fee, images, tags, featured, is_active, created_at, updated_at)
VALUES 
('Hotel Calbayog', 'Hotels', 'A comfortable hotel in the heart of Calbayog City with modern amenities and friendly staff.', 'Modern hotel in city center', 12.0680, 124.5965, 'City Proper, Calbayog City', '09171234567', 'info@hotelcalbayog.com', 'https://facebook.com/hotelcalbayog', 'https://hotelcalbayog.com', '24/7', '₱1,500-3,000/night', ARRAY['https://images.unsplash.com/photo-1566073771259-6a8506099945'], ARRAY['hotel', 'accommodation', 'city'], true, true, NOW(), NOW()),
('Samar Paradise Resort', 'Hotels', 'A beachfront resort offering stunning views and relaxing atmosphere perfect for vacationers.', 'Beachfront resort', 12.0550, 124.6100, 'Brgy. Mawacat, Calbayog City', '09181234567', 'resort@samarparadise.com', 'https://facebook.com/samarparadise', 'https://samarparadise.com', '7AM-10PM', '₱2,500-5,000/night', ARRAY['https://images.unsplash.com/photo-1582719508461-905c673771fd'], ARRAY['resort', 'beach', 'vacation'], true, true, NOW(), NOW()),
('Waterfalls Inn', 'Hotels', 'Cozy inn located near the famous waterfalls of Calbayog, perfect for nature lovers.', 'Near waterfalls', 12.1050, 124.5450, 'Brgy. Oquendo, Calbayog City', '09191234567', 'inn@waterfalls.com', 'https://facebook.com/waterfallsinn', 'https://waterfallsinn.com', '8AM-9PM', '₱800-1,500/night', ARRAY['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4'], ARRAY['inn', 'nature', 'budget'], false, true, NOW(), NOW()),
('City View Hotel', 'Hotels', 'Affordable hotel with panoramic city views and excellent service.', 'City view hotel', 12.0695, 124.5980, 'City Proper, Calbayog City', '09201234567', 'cityview@hotel.com', 'https://facebook.com/cityviewhotel', 'https://cityviewhotel.com', '24/7', '₱1,000-2,000/night', ARRAY['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa'], ARRAY['hotel', 'budget', 'city'], false, true, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Insert Beaches (Coastal areas of Calbayog)
INSERT INTO destinations (name, category, description, short_description, location_lat, location_lng, location_address, contact_phone, contact_email, contact_facebook, contact_website, opening_hours, entrance_fee, images, tags, featured, is_active, created_at, updated_at)
VALUES 
('Malajog Beach', 'Beaches', 'Famous beach resort with white sand and clear waters, one of the most popular in Calbayog.', 'Popular beach resort', 12.0320, 124.6250, 'Brgy. Malajog, Calbayog City', '09211234567', NULL, NULL, NULL, '6AM-6PM', '₱50/person', ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e'], ARRAY['beach', 'swimming', 'resort'], true, true, NOW(), NOW()),
('Mawacat Beach', 'Beaches', 'Hidden gem beach with rocky formations and excellent snorkeling spots.', 'Hidden beach gem', 12.0480, 124.6150, 'Brgy. Mawacat, Calbayog City', '09221234567', NULL, NULL, NULL, '6AM-6PM', 'Free', ARRAY['https://images.unsplash.com/photo-1505118380757-91f5f5632de0'], ARRAY['beach', 'snorkeling', 'hidden'], false, true, NOW(), NOW()),
('Daraga Beach', 'Beaches', 'Quiet beach perfect for relaxation and sunset watching.', 'Peaceful sunset beach', 12.0400, 124.6200, 'Brgy. Daraga, Calbayog City', '09231234567', NULL, NULL, NULL, '24/7', '₱20/person', ARRAY['https://images.unsplash.com/photo-1519046904884-53103b34b206'], ARRAY['beach', 'sunset', 'relaxation'], false, true, NOW(), NOW()),
('Pan-as Beach', 'Beaches', 'Secluded beach with pristine waters, perfect for a peaceful getaway.', 'Secluded beach', 12.0250, 124.6300, 'Brgy. Pan-as, Calbayog City', '09241234567', NULL, NULL, NULL, '6AM-6PM', 'Free', ARRAY['https://images.unsplash.com/photo-1473116763249-2faaef81ccda'], ARRAY['beach', 'peaceful', 'secluded'], false, true, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Insert Waterfalls (Oquendo District - famous for waterfalls)
INSERT INTO destinations (name, category, description, short_description, location_lat, location_lng, location_address, contact_phone, contact_email, contact_facebook, contact_website, opening_hours, entrance_fee, images, tags, featured, is_active, created_at, updated_at)
VALUES 
('Bangon-Bugtong Falls', 'Waterfalls', 'Twin waterfalls cascading into a natural pool, one of Calbayogs most famous attractions.', 'Twin waterfalls', 12.1100, 124.5400, 'Brgy. Oquendo, Calbayog City', '09251234567', NULL, 'https://facebook.com/bangonfalls', NULL, '8AM-5PM', '₱50/person', ARRAY['https://images.unsplash.com/photo-1432405972618-c60b0225b8f9'], ARRAY['waterfall', 'nature', 'twin-falls'], true, true, NOW(), NOW()),
('Tarangban Falls', 'Waterfalls', 'Majestic multi-tiered waterfall, one of the highest in Samar with stunning views.', 'Multi-tiered waterfall', 12.1200, 124.5350, 'Brgy. Oquendo, Calbayog City', '09261234567', NULL, NULL, NULL, '8AM-5PM', '₱30/person', ARRAY['https://images.unsplash.com/photo-1506905925346-21bda4d32df4'], ARRAY['waterfall', 'trekking', 'scenic'], true, true, NOW(), NOW()),
('Lulugayan Falls', 'Waterfalls', 'Series of cascading waterfalls forming natural pools perfect for swimming.', 'Cascading waterfalls', 12.1150, 124.5420, 'Brgy. Oquendo, Calbayog City', '09271234567', NULL, NULL, NULL, '8AM-5PM', '₱40/person', ARRAY['https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1'], ARRAY['waterfall', 'swimming', 'pools'], false, true, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Insert Food Places (City Proper area)
INSERT INTO destinations (name, category, description, short_description, location_lat, location_lng, location_address, contact_phone, contact_email, contact_facebook, contact_website, opening_hours, entrance_fee, images, tags, featured, is_active, created_at, updated_at)
VALUES 
('Calbayog Seafood Grill', 'Food', 'Fresh seafood dishes with local Samar flavors and cozy ambiance.', 'Fresh seafood', 12.0670, 124.5955, 'City Proper, Calbayog City', '09281234567', 'seafood@calbayog.com', 'https://facebook.com/calbayogseafood', NULL, '10AM-10PM', '₱200-500/person', ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de'], ARRAY['food', 'seafood', 'local'], true, true, NOW(), NOW()),
('Samar Delicacies', 'Food', 'Authentic Samar cuisine featuring traditional dishes and local specialties.', 'Local cuisine', 12.0700, 124.5990, 'City Proper, Calbayog City', '09291234567', NULL, 'https://facebook.com/samardelicacies', NULL, '8AM-8PM', '₱150-400/person', ARRAY['https://images.unsplash.com/photo-1504674900247-0877df9cc836'], ARRAY['food', 'local', 'traditional'], false, true, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Insert Nature Spots
INSERT INTO destinations (name, category, description, short_description, location_lat, location_lng, location_address, contact_phone, contact_email, contact_facebook, contact_website, opening_hours, entrance_fee, images, tags, featured, is_active, created_at, updated_at)
VALUES 
('Calbayog Zipline Eco Park', 'Nature', 'Adventure park with zipline and eco trails overlooking the city.', 'Zipline adventure park', 12.0750, 124.5850, 'Brgy. Tinaplacan, Calbayog City', '09301234567', 'ecopark@calbayog.gov.ph', 'https://facebook.com/calbayogecopark', 'https://calbayogecopark.com', '6AM-6PM', '₱150/person', ARRAY['https://images.unsplash.com/photo-1441974231531-c6227db76b6e'], ARRAY['nature', 'adventure', 'zipline'], true, true, NOW(), NOW()),
('Mapaso Hot Spring', 'Nature', 'Natural hot spring with therapeutic waters surrounded by lush greenery.', 'Natural hot spring', 12.0900, 124.5600, 'Brgy. Oquendo, Calbayog City', '09311234567', NULL, NULL, NULL, '6AM-5PM', '₱50/person', ARRAY['https://images.unsplash.com/photo-1448375240586-882707db888b'], ARRAY['nature', 'hotspring', 'relaxation'], false, true, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Insert Transport Locations
INSERT INTO destinations (name, category, description, short_description, location_lat, location_lng, location_address, contact_phone, contact_email, contact_facebook, contact_website, opening_hours, entrance_fee, images, tags, featured, is_active, created_at, updated_at)
VALUES
('Calbayog Airport', 'Transport', 'Calbayog Airport serving domestic flights to Manila and Cebu.', 'Domestic airport', 12.0727, 124.5447, 'Brgy. Rawis, Calbayog City', '09321234567', 'airport@calbayog.gov.ph', NULL, NULL, '24/7', 'Free', ARRAY['https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3'], ARRAY['transport', 'airport', 'flights'], true, true, NOW(), NOW()),
('Calbayog Integrated Bus Terminal', 'Transport', 'Main bus terminal for transportation to Tacloban, Catbalogan, and other destinations.', 'Main bus terminal', 12.0660, 124.5950, 'City Proper, Calbayog City', '09331234567', NULL, NULL, NULL, '5AM-9PM', 'Free', ARRAY['https://images.unsplash.com/photo-1544620347-c4fd4a3d5957'], ARRAY['transport', 'bus', 'terminal'], false, true, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Insert Accommodations (Hotels, Resorts, Inns)
INSERT INTO accommodations (name, type, description, short_description, images, location_lat, location_lng, location_address, contact_phone, contact_email, contact_facebook, contact_messenger, contact_website, amenities, room_types, price_range, price_min, price_max, star_rating, check_in, check_out, dot_accredited, featured, is_active, created_at, updated_at)
VALUES
('Hotel Calbayog', 'Hotel', 'A comfortable hotel in the heart of Calbayog City with modern amenities and friendly staff. Perfect for business and leisure travelers.', 'Modern hotel in city center', ARRAY['https://images.unsplash.com/photo-1566073771259-6a8506099945'], 12.0680, 124.5965, 'City Proper, Calbayog City', '09171234567', 'info@hotelcalbayog.com', 'https://facebook.com/hotelcalbayog', 'https://m.me/hotelcalbayog', 'https://hotelcalbayog.com', ARRAY['WiFi', 'Parking', 'Restaurant', 'AC', 'TV', 'Room Service'], ARRAY['Standard Room', 'Deluxe Room', 'Suite'], '₱1,500-3,000/night', 1500, 3000, 3, '2:00 PM', '12:00 PM', true, true, true, NOW(), NOW()),
('Samar Paradise Resort', 'Resort', 'A beachfront resort offering stunning views and relaxing atmosphere perfect for vacationers. Enjoy direct beach access and resort amenities.', 'Beachfront resort', ARRAY['https://images.unsplash.com/photo-1582719508461-905c673771fd'], 12.0550, 124.6100, 'Brgy. Mawacat, Calbayog City', '09181234567', 'resort@samarparadise.com', 'https://facebook.com/samarparadise', 'https://m.me/samarparadise', 'https://samarparadise.com', ARRAY['WiFi', 'Pool', 'Restaurant', 'Parking', 'Beach Access', 'Bar', 'Spa'], ARRAY['Beach Cottage', 'Ocean View Room', 'Family Suite'], '₱2,500-5,000/night', 2500, 5000, 4, '2:00 PM', '11:00 AM', true, true, true, NOW(), NOW()),
('Waterfalls Inn', 'Inn', 'Cozy inn located near the famous waterfalls of Calbayog, perfect for nature lovers and budget travelers. Experience the beauty of Samar waterfalls.', 'Near waterfalls', ARRAY['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4'], 12.1050, 124.5450, 'Brgy. Oquendo, Calbayog City', '09191234567', 'inn@waterfalls.com', 'https://facebook.com/waterfallsinn', 'https://m.me/waterfallsinn', 'https://waterfallsinn.com', ARRAY['WiFi', 'Parking', 'Restaurant'], ARRAY['Standard Room', 'Dormitory'], '₱800-1,500/night', 800, 1500, 2, '1:00 PM', '12:00 PM', false, false, true, NOW(), NOW()),
('City View Hotel', 'Hotel', 'Affordable hotel with panoramic city views and excellent service. Great value for money with clean rooms and friendly staff.', 'City view hotel', ARRAY['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa'], 12.0695, 124.5980, 'City Proper, Calbayog City', '09201234567', 'cityview@hotel.com', 'https://facebook.com/cityviewhotel', 'https://m.me/cityviewhotel', 'https://cityviewhotel.com', ARRAY['WiFi', 'Parking', 'AC', 'TV'], ARRAY['Standard Room', 'Deluxe Room'], '₱1,000-2,000/night', 1000, 2000, 2, '2:00 PM', '12:00 PM', false, false, true, NOW(), NOW()),
('Oquendo Pension House', 'Pension House', 'Budget-friendly pension house in Oquendo district, perfect for travelers exploring the waterfalls. Clean and simple accommodations.', 'Budget pension house', ARRAY['https://images.unsplash.com/photo-1631049307264-da0ec9d70304'], 12.1080, 124.5380, 'Brgy. Oquendo, Calbayog City', '09211234567', 'oquendo.pension@gmail.com', 'https://facebook.com/oquendopension', 'https://m.me/oquendopension', NULL, ARRAY['WiFi', 'Parking'], ARRAY['Fan Room', 'AC Room'], '₱500-1,000/night', 500, 1000, 1, '1:00 PM', '12:00 PM', false, false, true, NOW(), NOW()),
('Calbayog Homestay', 'Homestay', 'Experience local hospitality with our homestay option. Stay with a local family and experience authentic Calbayog culture.', 'Local homestay experience', ARRAY['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2'], 12.0650, 124.5970, 'City Proper, Calbayog City', '09221234567', 'homestay@calbayog.com', 'https://facebook.com/calbayoghomestay', 'https://m.me/calbayoghomestay', NULL, ARRAY['WiFi', 'Kitchen Access', 'Laundry'], ARRAY['Private Room', 'Shared Room'], '₱400-800/night', 400, 800, 0, '12:00 PM', '11:00 AM', false, false, true, NOW(), NOW()),
('Malajog Beach Resort', 'Resort', 'Beachfront resort at Malajog Beach with direct access to the famous white sand beach. Perfect for family vacations and beach lovers.', 'Beachfront at Malajog', ARRAY['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9'], 12.0320, 124.6250, 'Brgy. Malajog, Calbayog City', '09231234567', 'malajog@resort.com', 'https://facebook.com/malajogresort', 'https://m.me/malajogresort', 'https://malajogresort.com', ARRAY['WiFi', 'Pool', 'Restaurant', 'Beach Access', 'Parking', 'Bar'], ARRAY['Beach Villa', 'Garden Room', 'Family Cottage'], '₱3,000-6,000/night', 3000, 6000, 4, '2:00 PM', '11:00 AM', true, true, true, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Insert Tour Guides (Calbayog City Local Guides)
INSERT INTO guides (name, description, short_description, image, location_lat, location_lng, location_address, contact_phone, contact_email, contact_facebook, languages, specialties, rate, featured, is_active, created_at, updated_at)
VALUES
('Maria Santos', 'Licensed DOT-accredited tour guide with 10 years experience in Calbayog City. Expert in waterfall tours and cultural heritage sites. Fluent in English, Filipino, and Waray.', 'Expert waterfall tour guide', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330', 12.0680, 124.5965, 'City Proper, Calbayog City', '09171234567', 'maria.santos@calbayogtourism.com', 'https://facebook.com/mariasantosguide', ARRAY['English', 'Filipino', 'Waray'], ARRAY['Waterfalls', 'Heritage Sites', 'Cultural Tours'], '₱1,500/day', true, true, NOW(), NOW()),
('Jose Reyes', 'Adventure guide specializing in trekking, zipline, and outdoor activities. Knows all the hidden gems of Calbayog including off-the-beaten-path locations.', 'Adventure and trekking specialist', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d', 12.0750, 124.5850, 'Brgy. Tinaplacan, Calbayog City', '09181234567', 'jose.reyes@calbayogadventures.com', 'https://facebook.com/josereyesguide', ARRAY['English', 'Filipino'], ARRAY['Trekking', 'Zipline', 'Adventure Tours', 'Nature'], '₱1,800/day', true, true, NOW(), NOW()),
('Ana Cruz', 'Family-friendly tour guide perfect for groups with children. Specializes in beach tours, educational trips, and safe family adventures around Calbayog.', 'Family tour specialist', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80', 12.0550, 124.6100, 'Brgy. Mawacat, Calbayog City', '09191234567', 'ana.cruz@familytours.com', 'https://facebook.com/anacruzguide', ARRAY['English', 'Filipino', 'Waray'], ARRAY['Beach Tours', 'Family Trips', 'Educational Tours'], '₱1,200/day', false, true, NOW(), NOW()),
('Ricardo Tan', 'Local historian and cultural guide. Deep knowledge of Calbayogs history, traditions, and local stories. Perfect for heritage and cultural immersion tours.', 'Cultural and heritage expert', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e', 12.0695, 124.5980, 'City Proper, Calbayog City', '09201234567', 'ricardo.tan@calbayogheritage.com', 'https://facebook.com/ricardotanguide', ARRAY['English', 'Filipino', 'Waray'], ARRAY['Heritage', 'History', 'Cultural Immersion', 'Local Stories'], '₱1,500/day', true, true, NOW(), NOW()),
('Elena Martinez', 'Photography guide who knows the best spots for stunning photos in Calbayog. Expert in waterfall photography, sunset spots, and scenic locations.', 'Photography tour guide', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2', 12.0320, 124.6250, 'Brgy. Malajog, Calbayog City', '09211234567', 'elena.martinez@phototours.com', 'https://facebook.com/elenamartinezguide', ARRAY['English', 'Filipino'], ARRAY['Photography', 'Scenic Spots', 'Sunset Tours', 'Waterfalls'], '₱1,600/day', false, true, NOW(), NOW())
ON CONFLICT DO NOTHING; 
